#! /usr/bin/env python
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES.
#                         All rights reserved.
# SPDX-License-Identifier: Apache-2.0

import json

with open("compile_commands.json") as f:
    data = json.load(f)

for entry in data:
    path = entry["file"]
    if (
        path.endswith(".cc")
        and "pjrt/multimesh" in path
        and not path.endswith("cu.cc")
    ):
        print(path)
