#ifndef __LEGATE_XLA_C_H__
#define __LEGATE_XLA_C_H__

enum XlaOpCode {
  XLA_COMPILE_TASK,
  XLA_EXECUTE_TASK,
  XLA_COPY_DEVICE_TO_DEVICE,
  XLA_INIT_ZERO_TASK,
  XLA_SHARD_GETTER_TASK,
  XLA_SHARD_ASSEMBLE_TASK,
  XLA_STORE_BUFFER_ACTION,
  XLA_SET_SCALAR_TASK,
  XLA_MATERIALIZE_TASK,
  HLO_PROTOTYPE_LOAD,
  HLO_PROTOTYPE_EXECUTE,
  HLO_PROTOTYPE_DISTRIBUTED_INIT,
  HLO_PROTOTYPE_DISTRIBUTED_SHUTDOWN,
  HLO_PROTOTYPE_FILL,
};

enum XlaTunable {
  XLA_NUM_GPUS = 1,
  XLA_NUM_PROCS = 2,
};

#ifdef __cplusplus
extern "C" {
#endif

void legate_xla_perform_registration();

#ifdef __cplusplus
}
#endif

#endif